# GoReleaser configuration for Terraform Provider
# This creates standard Go releases + custom Terraform Registry format

version: 1

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}"
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
    binary: "{{ .ProjectName }}_v{{ .Version }}"

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  draft: false
  replace_existing_draft: true
  target_commitish: "{{ .Commit }}"
  discussion_category_name: General
  prerelease: auto
  mode: replace
  header: |
    ## Terraform Provider for Nosana {{ .Tag }}

    **Full Changelog**: https://github.com/HoomanDigital/terraform-provider-nosana/compare/{{ .PreviousTag }}...{{ .Tag }}

    The binaries published alongside this release are signed with GPG for enhanced security.

    ### 🚀 Installation

    ```hcl
    terraform {
      required_providers {
        nosana = {
          source  = "registry.terraform.io/HoomanDigital/nosana"
          version = "~> {{ .Major }}.{{ .Minor }}"
        }
      }
    }
    ```

    ### 📋 Prerequisites

    - Nosana CLI: `npm install -g @nosana/cli`
    - Funded Solana wallet with SOL and NOS tokens
    - Valid Nosana keypair

  footer: |
    ## 🌐 Registry

    This provider is available on the [Terraform Registry](https://registry.terraform.io/providers/HoomanDigital/nosana).

    ## 📚 Documentation

    - [Provider Documentation](https://registry.terraform.io/providers/HoomanDigital/nosana/latest/docs)
    - [GitHub Repository](https://github.com/HoomanDigital/terraform-provider-nosana)
    - [Examples](https://github.com/HoomanDigital/terraform-provider-nosana/tree/main/examples)

changelog:
  use: github
  sort: asc
  abbrev: 0
  groups:
    - title: "🆕 New Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 100
    - title: "🐛 Bug Fixes"
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 200
    - title: "📚 Documentation"
      regexp: '^.*?docs(\(.+\))??!?:.+$'
      order: 400
    - title: "🔧 Dependencies"
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: "🔨 Other Changes"
      order: 9999